name: flutter_rust_demo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  ffi: ^2.1.2
  file_picker: ^8.0.3
  flutter:
    sdk: flutter
  flutter_chat_ui: ^1.6.12
  flutter_rust_bridge: ^1.82.6
  freezed_annotation: ^2.4.1
  image_picker: ^1.1.1
  open_filex: ^4.4.0
  path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  ffigen: ^9.0.0
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
